### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by Priyansh2** [clee704/audiodiff#1]
When try to install to install this with python3-pip or pip3 it gave me following error:- 
` Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sv4duabq/mutagen/setup.py", line 29
        except EnvironmentError, err:
                               ^
    SyntaxError: invalid syntax
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sv4duabq/mutagen/

`

**Comment by OberoiSahaj** [comment]
I am facing the same issue!

**Comment by RenukaL** [comment]
I am facing same issue...Please guide me...

**Comment by Jainu-s** [comment]
I too facing the same issue please fix the bug.

**Comment by viswabhaskar** [comment]
please fix the problem same issue i am getting

**Comment by laerm0** [comment]
Bleh, still happening.

**Comment by laerm0** [comment]
Aha: @SteveClement has upgraded this and `mutagenwrapper` to Python 3. 🎉  You'll need to install from his latest commits using the `python -m pip install git+longURLofthecommithash` method but it works fine. 

Thanks a lot, Steve!
