### ISSUE TITLE
audiodiff binary issue

### ISSUE THREAD

**Issue by pullannagari-babu** [clee704/audiodiff#2]
Hello All,

i created recipe using devtool, i built successfully but audiodiff binary facing issue.

audiodiff_git.bb

SUMMARY = "Small library for comparing audio files"
HOMEPAGE = "https://github.com/clee704/audiodiff"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=c84e574e9e671e5e29adcc6ab80450f8"

SRC_URI = "git://github.com/adisakshya/audiodiff.git;protocol=https"
PV = "1.0+git${SRCPV}"
SRCREV = "34bf2a0f6f7583959ad7cca540208bd25d056297"

S = "${WORKDIR}/git"
inherit setuptools3
RDEPENDS_${PN} += "python3-core"

#issue is attached log below.

root@Exaleap-Unmatched-Linux-1:~# ls
lxqt  sp02_noisy.wav  sp03_clean.wav
root@Exaleap-Unmatched-Linux-1:~# audiodiff sp02_noisy.wav sp03_clean.wav 
Traceback (most recent call last):
  File "/usr/bin/audiodiff", line 33, in <module>
    sys.exit(load_entry_point('audiodiff==0.3.0', 'console_scripts', 'audiodiff')())
  File "/usr/bin/audiodiff", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/audiodiff/commandlinetool.py", line 284
    print message.encode(_encoding_for(sys.stdout), 'replace')
          ^
SyntaxError: invalid syntax

Please give any solution....

Thanks
Babu

**Comment by pullannagari-babu** [comment]
Hello  choonegmin

Please help me out this issue @clee704.
